# Meta
site_name: Docker Info Pack
site_author: 'Joost van der Griendt'
site_url: 'https://joostvdg.github.io/'

# Docs dir
docs_dir: 'docs'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/joostvdg/docker-info-pack'

# Copyright
copyright: 'Copyright &copy; 2017 Joost van der Griendt'

pages:
- Home: index.md
- Docker:
    - Index: docker/index.md
    - Swarm Mode: docker/swarm-mode.md
    - Docker & Jenkins: docker/jenkins.md
- Azure:
    - Index: azure/index.md
    - ACS Engine: azure/acs-engine.md

# Theme
theme: 'material'

# Extra Options
extra:
  palette:
    primary: 'lime'
    accent: 'yellow'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde


